### ISSUE TITLE
Class not found error

### ISSUE THREAD

**Issue by PrajapatiChirag** [sivajik34/Magento2-Product-Attachments#1]
it's give me fatal error on compile time ,

Fatal error:  Class 'Magento\Catalog\Model\ResourceModel\Setup' not found in [MAGENTO_ROOT]/app/code/Web4pro/Attachments/Model/ResourceModel/Setup.php on line 20

**Comment by sivajik34** [comment]
You can delete Web4pro/Attachments/Model/ResourceModel/Setup.php file
